test:
  value: 张三
  enc-value: ENC(AbGFku1MadQRHVLewgyTzw==)

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
      name: myboot
      url: jdbc:mysql://localhost:3306/myboot?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.zhangype.myboot.modules
  configuration:
    map-underscore-to-camel-case: true